# Generated by Django 5.0.2 on 2024-04-17 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xes_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xes'])])),
                ('owl_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['owl'])])),
                ('xes_content', models.TextField()),
                ('owl_content', models.TextField()),
                ('xes_file_path', models.CharField(max_length=255)),
                ('owl_file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
