# Generated by Django 5.0.2 on 2024-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOEA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='custom_ontology_used',
            field=models.BooleanField(default=False),
        ),
    ]
